### ISSUE TITLE
The asynchronous operation has not completed

### ISSUE THREAD

**Issue by dxq0126** [dotnet/samples#3763]
Unhandled Exception: System.InvalidOperationException: The asynchronous operation has not completed.
   at System.Threading.Channels.AsyncOperation.ThrowIncompleteOperationException()
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()
   at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
   at Microsoft.ML.Trainers.StochasticTrainerBase`2.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at GitHubIssueClassification.Program.BuildAndTrainModel(IDataView trainingDataView, IEstimator`1 pipeline) in E:\MyProject\GitHubIssueClassification\GitHubIssueClassification\Program.cs:line 103
   at GitHubIssueClassification.Program.Main(String[] args) in E:\MyProject\GitHubIssueClassification\GitHubIssueClassification\Program.cs:line 51

**Comment by MilanHajicek** [comment]
The same has happened to me.
=============== Loading Dataset  ===============
=============== Finished Loading Dataset  ===============
=============== Processing Data ===============
=============== Finished Processing Data ===============
=============== Training the model  ===============
Unhandled exception. System.InvalidOperationException: The asynchronous operation has not completed.
   at System.Threading.Channels.AsyncOperation.ThrowIncompleteOperationException()
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()
   at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
   at Microsoft.ML.Trainers.StochasticTrainerBase`2.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at GitHubIssueClassification.Program.BuildAndTrainModel(IDataView trainingDataView, IEstimator`1 pipeline) in C:\Users\milan\Source\Repos\GitHubIssueClassification\Program.cs:line 102
   at GitHubIssueClassification.Program.Main(String[] args) in C:\Users\milan\Source\Repos\GitHubIssueClassification\Program.cs:line 50

**Comment by 54mu3l** [comment]
Same here.

> System.InvalidOperationException
>   HResult=0x80131509
>   Message=The asynchronous operation has not completed.
>   Source=System.Threading.Channels
>   StackTrace:
>    at System.Threading.Channels.AsyncOperation.ThrowIncompleteOperationException()
>    at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
>    at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
>    at Microsoft.ML.Data.RootCursorBase.MoveNext()
>    at Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()
>    at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
>    at Microsoft.ML.Trainers.StochasticTrainerBase`2.TrainModelCore(TrainContext context)
>    at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
>    at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
>    at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
>    at worksforus.Api.AI.SmartSuggestions.BuildAndTrainModel(IDataView trainingDataView, IEstimator`1 pipeline) in C:\Projekte\dev\worksforus\worksforus.Api\AI\SmartSuggestions.cs:line 116
>    at worksforus.Api.AI.SmartSuggestions.Init() in C:\Projekte\dev\worksforus\worksforus.Api\AI\SmartSuggestions.cs:line 64
>    at worksforus.Api.Startup.ConfigureServices(IServiceCollection services) in C:\Projekte\dev\worksforus\worksforus.Api\Startup.cs:line 98
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
>    at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)

**Comment by IEvangelist** [comment]
Hi @dxq0126, @MilanHajicek, and @54mu3l - could you please tell me what project you're seeing this issue in?

**Comment by MilanHajicek** [comment]
Hi David,

 

It goes about the GitHubIssueClassification

 

Have a look at the error details when running in the VS2019.

 

System.InvalidOperationException

  HResult=0x80131509

  Zpráva=The asynchronous operation has not completed.

  Zdroj=System.Threading.Channels

  StackTrace:

   at System.Threading.Channels.AsyncOperation.ThrowIncompleteOperationException()

   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)

   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()

   at Microsoft.ML.Data.RootCursorBase.MoveNext()

   at Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()

   at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)

   at Microsoft.ML.Trainers.StochasticTrainerBase`2.TrainModelCore(TrainContext context)

   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)

   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)

   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)

   at GitHubIssueClassification.Program.BuildAndTrainModel(IDataView trainingDataView, IEstimator`1 pipeline) in C:\Users\milan\Source\Repos\GitHubIssueClassification\Program.cs:line 102

   at GitHubIssueClassification.Program.Main(String[] args) in C:\Users\milan\Source\Repos\GitHubIssueClassification\Program.cs:line 50

 

Thanks you for your feedback,

 

Milan

**Comment by dxq0126** [comment]
> Hi @dxq0126, @MilanHajicek, and @54mu3l - could you please tell me what project you're seeing this issue in?

the project is at
machine-learning/tutorials/GitHubIssueClassification/GitHubIssueClassification

and the environment is
.net core 2.1
Microsoft.ML(1.5.1)

**Comment by 54mu3l** [comment]
> Hi @dxq0126, @MilanHajicek, and @54mu3l - could you please tell me what project you're seeing this issue in?

same project as mentioned above

with .net core 3.1
Microsoft.ML (1.5.1)
VS2019

**Comment by cesarlinux** [comment]
Hello, the same error here
using:
.net core 3.1
Microsoft.ML 1.5.1
VS2019 16.6.5

**Comment by cesarlinux** [comment]
The same code is working with the 
Microsoft.ML 1.5.2-29219-1 from the [daily NuGet feed](https://pkgs.dev.azure.com/dnceng/public/_packaging/MachineLearning/nuget/v3/index.json)
